# Generated by Django 4.0.2 on 2022-02-25 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Essay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgCover', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('txtIntro', models.CharField(max_length=200)),
                ('rawHtmlData', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('createAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
