# Generated by Django 4.0.2 on 2022-02-25 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanglerng', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essay',
            name='rawHtmlData',
            field=models.TextField(),
        ),
    ]
