# Generated by Django 4.0.2 on 2022-02-25 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanglerng', '0002_alter_essay_rawhtmldata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essay',
            name='imgCover',
            field=models.FileField(upload_to='media/%Y/%m/%d/'),
        ),
    ]
