# Generated by Django 4.0.2 on 2022-02-25 09:51

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('nanglerng', '0003_alter_essay_imgcover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essay',
            name='rawHtmlData',
            field=django_quill.fields.QuillField(),
        ),
    ]
