# Generated by Django 4.0.2 on 2022-02-28 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanglerng', '0005_aboutus_post_typepost_tags_postimage_post_typepost'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='main_flag',
            field=models.BooleanField(default=False),
        ),
    ]
