# Generated by Django 4.0.2 on 2022-02-28 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nanglerng', '0006_post_main_flag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='main_flag',
            new_name='mainFlag',
        ),
    ]
