# Generated by Django 4.0.2 on 2022-03-01 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanglerng', '0007_rename_main_flag_post_mainflag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-createAt']},
        ),
        migrations.AddField(
            model_name='post',
            name='imgCover',
            field=models.FileField(blank=True, upload_to='media/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='essay',
            name='imgCover',
            field=models.FileField(blank=True, upload_to='media/%Y/%m/%d/'),
        ),
    ]
