# Generated by Django 4.0.2 on 2022-03-25 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nanglerng', '0009_post_tags_delete_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nanglerng.post'),
        ),
    ]
