# Generated by Django 3.2.12 on 2022-04-06 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanglerng', '0010_post_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='activeEvent',
            field=models.BooleanField(default=False),
        ),
    ]
