# Generated by Django 4.0.2 on 2022-04-11 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nanglerng', '0013_rename_contribute_post_contributor_alter_post_lat_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='category',
        ),
        migrations.RemoveField(
            model_name='post',
            name='culture',
        ),
    ]
