# Generated by Django 4.0.2 on 2022-05-09 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanglerng', '0014_rename_author_post_category_remove_post_culture'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='eventDateTime',
            field=models.DateField(blank=True, null=True),
        ),
    ]
